# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsTimeline.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsTimeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyticsTimeline.proto\x12\x15rv.analytics.timeline\"t\n\x06\x41\x63tion\x12=\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32(.rv.analytics.timeline.Action.ActionType\"+\n\nActionType\x12\x08\n\x04PLAY\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\t\n\x05RESET\x10\x02\"\x0b\n\tRecordCue\"\xfd\x01\n\nCueTrigger\x12\x43\n\x0ctrigger_type\x18\x01 \x01(\x0e\x32-.rv.analytics.timeline.CueTrigger.TriggerType\x12\x45\n\rtiming_source\x18\x02 \x01(\x0e\x32..rv.analytics.timeline.CueTrigger.TimingSource\":\n\x0bTriggerType\x12\t\n\x05SLIDE\x10\x00\x12\t\n\x05MEDIA\x10\x01\x12\t\n\x05\x41UDIO\x10\x02\x12\n\n\x06\x41\x43TION\x10\x03\"\'\n\x0cTimingSource\x12\x0c\n\x08INTERNAL\x10\x00\x12\t\n\x05SMPTE\x10\x01\x42S\xf8\x01\x01\xaa\x02\x37Pro.SerializationInterop.RVProtoData.Analytics.Timeline\xba\x02\x13\x41nalytics_Timeline_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsTimeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\0027Pro.SerializationInterop.RVProtoData.Analytics.Timeline\272\002\023Analytics_Timeline_'
  _globals['_ACTION']._serialized_start=50
  _globals['_ACTION']._serialized_end=166
  _globals['_ACTION_ACTIONTYPE']._serialized_start=123
  _globals['_ACTION_ACTIONTYPE']._serialized_end=166
  _globals['_RECORDCUE']._serialized_start=168
  _globals['_RECORDCUE']._serialized_end=179
  _globals['_CUETRIGGER']._serialized_start=182
  _globals['_CUETRIGGER']._serialized_end=435
  _globals['_CUETRIGGER_TRIGGERTYPE']._serialized_start=336
  _globals['_CUETRIGGER_TRIGGERTYPE']._serialized_end=394
  _globals['_CUETRIGGER_TIMINGSOURCE']._serialized_start=396
  _globals['_CUETRIGGER_TIMINGSOURCE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
