# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsMediaManagement.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsMediaManagement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61nalyticsMediaManagement.proto\x12\x1crv.analytics.mediamanagement\"\xe2\x01\n\x14InstallationComplete\x12M\n\x07success\x18\x01 \x01(\x0b\x32:.rv.analytics.mediamanagement.InstallationComplete.SuccessH\x00\x12M\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32:.rv.analytics.mediamanagement.InstallationComplete.FailureH\x00\x1a\t\n\x07Success\x1a\x18\n\x07\x46\x61ilure\x12\r\n\x05\x65rror\x18\x01 \x01(\tB\x07\n\x05state\"\xe5\x01\n\x15\x42ootstrappingComplete\x12N\n\x07success\x18\x01 \x01(\x0b\x32;.rv.analytics.mediamanagement.BootstrappingComplete.SuccessH\x00\x12N\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32;.rv.analytics.mediamanagement.BootstrappingComplete.FailureH\x00\x1a\t\n\x07Success\x1a\x18\n\x07\x46\x61ilure\x12\r\n\x05\x65rror\x18\x01 \x01(\tB\x07\n\x05state\"\x1f\n\x0eMessageFailure\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"\x18\n\x16UnexpectedlyNotRunning\"\x8f\x01\n\x11\x43onnectionChanged\x12\x44\n\x05state\x18\x01 \x01(\x0e\x32\x35.rv.analytics.mediamanagement.ConnectionChanged.State\"4\n\x05State\x12\x13\n\x0fSTATE_CONNECTED\x10\x00\x12\x16\n\x12STATE_DISCONNECTED\x10\x01\"4\n\x13\x41\x64\x64\x65\x64MediaReference\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x0f\n\rNotRespondingBa\xf8\x01\x01\xaa\x02>Pro.SerializationInterop.RVProtoData.Analytics.MediaManagement\xba\x02\x1a\x41nalytics_MediaManagement_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsMediaManagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002>Pro.SerializationInterop.RVProtoData.Analytics.MediaManagement\272\002\032Analytics_MediaManagement_'
  _globals['_INSTALLATIONCOMPLETE']._serialized_start=65
  _globals['_INSTALLATIONCOMPLETE']._serialized_end=291
  _globals['_INSTALLATIONCOMPLETE_SUCCESS']._serialized_start=247
  _globals['_INSTALLATIONCOMPLETE_SUCCESS']._serialized_end=256
  _globals['_INSTALLATIONCOMPLETE_FAILURE']._serialized_start=258
  _globals['_INSTALLATIONCOMPLETE_FAILURE']._serialized_end=282
  _globals['_BOOTSTRAPPINGCOMPLETE']._serialized_start=294
  _globals['_BOOTSTRAPPINGCOMPLETE']._serialized_end=523
  _globals['_BOOTSTRAPPINGCOMPLETE_SUCCESS']._serialized_start=247
  _globals['_BOOTSTRAPPINGCOMPLETE_SUCCESS']._serialized_end=256
  _globals['_BOOTSTRAPPINGCOMPLETE_FAILURE']._serialized_start=258
  _globals['_BOOTSTRAPPINGCOMPLETE_FAILURE']._serialized_end=282
  _globals['_MESSAGEFAILURE']._serialized_start=525
  _globals['_MESSAGEFAILURE']._serialized_end=556
  _globals['_UNEXPECTEDLYNOTRUNNING']._serialized_start=558
  _globals['_UNEXPECTEDLYNOTRUNNING']._serialized_end=582
  _globals['_CONNECTIONCHANGED']._serialized_start=585
  _globals['_CONNECTIONCHANGED']._serialized_end=728
  _globals['_CONNECTIONCHANGED_STATE']._serialized_start=676
  _globals['_CONNECTIONCHANGED_STATE']._serialized_end=728
  _globals['_ADDEDMEDIAREFERENCE']._serialized_start=730
  _globals['_ADDEDMEDIAREFERENCE']._serialized_end=782
  _globals['_NOTRESPONDING']._serialized_start=784
  _globals['_NOTRESPONDING']._serialized_end=799
# @@protoc_insertion_point(module_scope)
