# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsProContent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsProContent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61nalyticsProContent.proto\x12\x17rv.analytics.procontent\"\x0e\n\x0cMediaBinView\"\n\n\x08\x44ownload\"\x0f\n\rDownloadRetryBW\xf8\x01\x01\xaa\x02\x39Pro.SerializationInterop.RVProtoData.Analytics.ProContent\xba\x02\x15\x41nalytics_ProContent_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsProContent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\0029Pro.SerializationInterop.RVProtoData.Analytics.ProContent\272\002\025Analytics_ProContent_'
  _globals['_MEDIABINVIEW']._serialized_start=54
  _globals['_MEDIABINVIEW']._serialized_end=68
  _globals['_DOWNLOAD']._serialized_start=70
  _globals['_DOWNLOAD']._serialized_end=80
  _globals['_DOWNLOADRETRY']._serialized_start=82
  _globals['_DOWNLOADRETRY']._serialized_end=97
# @@protoc_insertion_point(module_scope)
