# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsPowerPoint.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsPowerPoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61nalyticsPowerPoint.proto\x12\x17rv.analytics.powerpoint\"|\n\x10ImportPowerPoint\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.rv.analytics.powerpoint.ImportType\x12\x35\n\x06\x66ormat\x18\x02 \x01(\x0e\x32%.rv.analytics.powerpoint.ImportFormat*Y\n\nImportType\x12\x14\n\x10SLIDES_AS_IMAGES\x10\x00\x12\r\n\tTEXT_ONLY\x10\x01\x12\x13\n\x0fTEXT_AND_IMAGES\x10\x02\x12\x11\n\rCORE_OPEN_XML\x10\x03*-\n\x0cImportFormat\x12\n\n\x06UNKOWN\x10\x00\x12\x07\n\x03PPT\x10\x01\x12\x08\n\x04PPTX\x10\x02\x42\x1b\xf8\x01\x01\xba\x02\x15\x41nalytics_PowerPoint_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsPowerPoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\272\002\025Analytics_PowerPoint_'
  _globals['_IMPORTTYPE']._serialized_start=180
  _globals['_IMPORTTYPE']._serialized_end=269
  _globals['_IMPORTFORMAT']._serialized_start=271
  _globals['_IMPORTFORMAT']._serialized_end=316
  _globals['_IMPORTPOWERPOINT']._serialized_start=54
  _globals['_IMPORTPOWERPOINT']._serialized_end=178
# @@protoc_insertion_point(module_scope)
