# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsCreate.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsCreate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61nalyticsCreate.proto\x12\x13rv.analytics.create\"\x8b\x01\n\x07Library\x12\x33\n\x06source\x18\x01 \x01(\x0e\x32#.rv.analytics.create.Library.Source\"K\n\x06Source\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10\x41PPLICATION_MENU\x10\x01\x12\x1e\n\x1aLIBRARY_OUTLINE_ADD_BUTTON\x10\x02\"\xaa\x02\n\x08Playlist\x12\x34\n\x06source\x18\x01 \x01(\x0e\x32$.rv.analytics.create.Playlist.Source\x12\x30\n\x04type\x18\x02 \x01(\x0e\x32\".rv.analytics.create.Playlist.Type\"R\n\x06Source\x12\x12\n\x0eSOURCE_UNKNOWN\x10\x00\x12\x14\n\x10\x41PPLICATION_MENU\x10\x01\x12\x1e\n\x1aLIBRARY_OUTLINE_ADD_BUTTON\x10\x02\"b\n\x04Type\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x10\n\x0cPRESENTATION\x10\x01\x12\x13\n\x0fPLANNING_CENTER\x10\x02\x12\n\n\x06\x46OLDER\x10\x03\x12\x15\n\x11TEMPLATE_PLAYLIST\x10\x04\"\xc1\x01\n\x0cPresentation\x12\x38\n\x06source\x18\x01 \x01(\x0e\x32(.rv.analytics.create.Presentation.Source\"w\n\x06Source\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10\x41PPLICATION_MENU\x10\x01\x12\x1e\n\x1aLIBRARY_OUTLINE_ADD_BUTTON\x10\x02\x12\x15\n\x11\x44\x45TAIL_ADD_BUTTON\x10\x03\x12\x13\n\x0fUNLINKED_HEADER\x10\x04\"\x8e\x01\n\x10TemplatePlaylist\x12\x18\n\x10total_item_count\x18\x01 \x01(\x05\x12\x14\n\x0cheader_count\x18\x02 \x01(\x05\x12\x19\n\x11placeholder_count\x18\x03 \x01(\x05\x12\x1a\n\x12presentation_count\x18\x04 \x01(\x05\x12\x13\n\x0bmedia_count\x18\x05 \x01(\x05\x42O\xf8\x01\x01\xaa\x02\x35Pro.SerializationInterop.RVProtoData.Analytics.Create\xba\x02\x11\x41nalytics_Create_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsCreate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\0025Pro.SerializationInterop.RVProtoData.Analytics.Create\272\002\021Analytics_Create_'
  _globals['_LIBRARY']._serialized_start=47
  _globals['_LIBRARY']._serialized_end=186
  _globals['_LIBRARY_SOURCE']._serialized_start=111
  _globals['_LIBRARY_SOURCE']._serialized_end=186
  _globals['_PLAYLIST']._serialized_start=189
  _globals['_PLAYLIST']._serialized_end=487
  _globals['_PLAYLIST_SOURCE']._serialized_start=305
  _globals['_PLAYLIST_SOURCE']._serialized_end=387
  _globals['_PLAYLIST_TYPE']._serialized_start=389
  _globals['_PLAYLIST_TYPE']._serialized_end=487
  _globals['_PRESENTATION']._serialized_start=490
  _globals['_PRESENTATION']._serialized_end=683
  _globals['_PRESENTATION_SOURCE']._serialized_start=564
  _globals['_PRESENTATION_SOURCE']._serialized_end=683
  _globals['_TEMPLATEPLAYLIST']._serialized_start=686
  _globals['_TEMPLATEPLAYLIST']._serialized_end=828
# @@protoc_insertion_point(module_scope)
