# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsMultiTracks.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsMultiTracks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61nalyticsMultiTracks.proto\x12\x18rv.analytics.multitracks\"|\n\x07Startup\x12\x33\n\tchart_pro\x18\x01 \x01(\x0e\x32 .rv.analytics.multitracks.Status\x12<\n\x12propresenter_addon\x18\x02 \x01(\x0e\x32 .rv.analytics.multitracks.Status\"\xa5\x01\n\x06Import\x12\x33\n\tchart_pro\x18\x01 \x01(\x0e\x32 .rv.analytics.multitracks.Status\x12<\n\x12propresenter_addon\x18\x02 \x01(\x0e\x32 .rv.analytics.multitracks.Status\x12\x19\n\x11\x63harts_automation\x18\x03 \x01(\x08\x12\r\n\x05lines\x18\x04 \x01(\x05*1\n\x06Status\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\r\n\tCANCELLED\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x42Y\xf8\x01\x01\xaa\x02:Pro.SerializationInterop.RVProtoData.Analytics.MultiTracks\xba\x02\x16\x41nalytics_MultiTracks_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsMultiTracks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002:Pro.SerializationInterop.RVProtoData.Analytics.MultiTracks\272\002\026Analytics_MultiTracks_'
  _globals['_STATUS']._serialized_start=350
  _globals['_STATUS']._serialized_end=399
  _globals['_STARTUP']._serialized_start=56
  _globals['_STARTUP']._serialized_end=180
  _globals['_IMPORT']._serialized_start=183
  _globals['_IMPORT']._serialized_end=348
# @@protoc_insertion_point(module_scope)
