# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsTimecode.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsTimecode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyticsTimecode.proto\x12\x15rv.analytics.timecode\"X\n\x07Startup\x12\x1b\n\x13is_input_configured\x18\x01 \x01(\x08\x12\x12\n\nis_enabled\x18\x02 \x01(\x08\x12\x1c\n\x14is_playlist_selected\x18\x03 \x01(\x08\"N\n\x08\x41\x63tivate\x12\x1b\n\x13playlist_item_count\x18\x01 \x01(\x05\x12\x11\n\tcue_count\x18\x02 \x01(\x05\x12\x12\n\nis_startup\x18\x03 \x01(\x08\x42S\xf8\x01\x01\xaa\x02\x37Pro.SerializationInterop.RVProtoData.Analytics.Timecode\xba\x02\x13\x41nalytics_Timecode_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsTimecode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\0027Pro.SerializationInterop.RVProtoData.Analytics.Timecode\272\002\023Analytics_Timecode_'
  _globals['_STARTUP']._serialized_start=50
  _globals['_STARTUP']._serialized_end=138
  _globals['_ACTIVATE']._serialized_start=140
  _globals['_ACTIVATE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
