# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsPlaybackMarker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsPlaybackMarker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61nalyticsPlaybackMarker.proto\x12\x1brv.analytics.playbackmarker\"\x89\x01\n\x0c\x43reateMarker\x12\x44\n\x08location\x18\x01 \x01(\x0e\x32\x32.rv.analytics.playbackmarker.CreateMarker.Location\"3\n\x08Location\x12\r\n\tINSPECTOR\x10\x00\x12\x0b\n\x07SIDEBAR\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x42_\xf8\x01\x01\xaa\x02=Pro.SerializationInterop.RVProtoData.Analytics.PlaybackMarker\xba\x02\x19\x41nalytics_PlaybackMarker_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsPlaybackMarker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002=Pro.SerializationInterop.RVProtoData.Analytics.PlaybackMarker\272\002\031Analytics_PlaybackMarker_'
  _globals['_CREATEMARKER']._serialized_start=63
  _globals['_CREATEMARKER']._serialized_end=200
  _globals['_CREATEMARKER_LOCATION']._serialized_start=149
  _globals['_CREATEMARKER_LOCATION']._serialized_end=200
# @@protoc_insertion_point(module_scope)
