# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyticsSync.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyticsSync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61nalyticsSync.proto\x12\x11rv.analytics.sync\"\xec\x01\n\x05Local\x12\x30\n\tsync_type\x18\x01 \x01(\x0e\x32\x1d.rv.analytics.sync.Local.Type\x12\x17\n\x0finclude_library\x18\x02 \x01(\x08\x12\x15\n\rinclude_media\x18\x03 \x01(\x08\x12\x19\n\x11include_playlists\x18\x04 \x01(\x08\x12\x16\n\x0einclude_themes\x18\x05 \x01(\x08\x12\x1d\n\x15include_support_files\x18\x06 \x01(\x08\x12\x15\n\rreplace_files\x18\x07 \x01(\x08\"\x18\n\x04Type\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\"~\n\x19WebSocketConnectionFailed\x12\x39\n\x06reason\x18\x01 \x01(\x0e\x32).rv.analytics.sync.WebSocketFailureReason\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x19\n\x11\x65rror_description\x18\x03 \x01(\t*i\n\x16WebSocketFailureReason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0e\x41UTHENTICATION\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x0f\n\x0bNO_INTERNET\x10\x03\x12\x10\n\x0cSERVER_ERROR\x10\x04\x42K\xf8\x01\x01\xaa\x02\x33Pro.SerializationInterop.RVProtoData.Analytics.Sync\xba\x02\x0f\x41nalytics_Sync_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsSync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\0023Pro.SerializationInterop.RVProtoData.Analytics.Sync\272\002\017Analytics_Sync_'
  _globals['_WEBSOCKETFAILUREREASON']._serialized_start=409
  _globals['_WEBSOCKETFAILUREREASON']._serialized_end=514
  _globals['_LOCAL']._serialized_start=43
  _globals['_LOCAL']._serialized_end=279
  _globals['_LOCAL_TYPE']._serialized_start=255
  _globals['_LOCAL_TYPE']._serialized_end=279
  _globals['_WEBSOCKETCONNECTIONFAILED']._serialized_start=281
  _globals['_WEBSOCKETCONNECTIONFAILED']._serialized_end=407
# @@protoc_insertion_point(module_scope)
