# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rror.proto\x12\x0b\x61pplication\"S\n\x05\x45rror\x12\'\n\x07service\x18\x01 \x01(\x0e\x32\x16.application.ServiceID\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"s\n\x0eResultEnvelope\x12,\n\x02ok\x18\x01 \x01(\x0b\x32\x1e.application.ResultEnvelope.OkH\x00\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.application.ErrorH\x00\x1a\x04\n\x02OkB\x08\n\x06result*i\n\tServiceID\x12\x0f\n\x0b\x41PPLICATION\x10\x00\x12\t\n\x05MEDIA\x10\x01\x12\x11\n\rFEATURE_FLAGS\x10\x02\x12\x10\n\x0cREGISTRATION\x10\x03\x12\x0c\n\x08\x44OCUMENT\x10\x04\x12\r\n\tWORKSPACE\x10\x05*\x85\x01\n\tErrorCode\x12\x0b\n\x07RUNTIME\x10\x00\x12\x08\n\x04\x43\x41LL\x10\x01\x12\n\n\x06PARAMS\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03\x12\t\n\x05PANIC\x10\x04\x12\x08\n\x04JOIN\x10\x05\x12\x07\n\x03HID\x10\x06\x12\n\n\x06REMOTE\x10\x07\x12\x0e\n\nDEPENDENCY\x10\x08\x12\x11\n\rMEDIA_VERSION\x10\tBI\xaa\x02\x30Pro.SerializationInterop.RVProtoData.Application\xba\x02\x13RVData_Application_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0020Pro.SerializationInterop.RVProtoData.Application\272\002\023RVData_Application_'
  _globals['_SERVICEID']._serialized_start=230
  _globals['_SERVICEID']._serialized_end=335
  _globals['_ERRORCODE']._serialized_start=338
  _globals['_ERRORCODE']._serialized_end=471
  _globals['_ERROR']._serialized_start=28
  _globals['_ERROR']._serialized_end=111
  _globals['_RESULTENVELOPE']._serialized_start=113
  _globals['_RESULTENVELOPE']._serialized_end=228
  _globals['_RESULTENVELOPE_OK']._serialized_start=214
  _globals['_RESULTENVELOPE_OK']._serialized_end=218
# @@protoc_insertion_point(module_scope)
