# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature-flags.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'feature-flags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x65\x61ture-flags.proto\x12\rfeature_flags\"\x10\n\x0e\x43reationOption\"%\n\x04\x46lag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\".\n\x08\x41llFlags\x12\"\n\x05\x66lags\x18\x01 \x03(\x0b\x32\x13.feature_flags.Flag\"\xb4\x01\n\x0cNotification\x12,\n\tall_flags\x18\x01 \x01(\x0b\x32\x17.feature_flags.AllFlagsH\x00\x12O\n\x14unsubscribe_complete\x18\x02 \x01(\x0b\x32/.feature_flags.Notification.UnsubscribeCompleteH\x00\x1a\x15\n\x13UnsubscribeCompleteB\x0e\n\x0cnotificationBK\xaa\x02\x31Pro.SerializationInterop.RVProtoData.FeatureFlags\xba\x02\x14RVData_FeatureFlags_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_flags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0021Pro.SerializationInterop.RVProtoData.FeatureFlags\272\002\024RVData_FeatureFlags_'
  _globals['_CREATIONOPTION']._serialized_start=38
  _globals['_CREATIONOPTION']._serialized_end=54
  _globals['_FLAG']._serialized_start=56
  _globals['_FLAG']._serialized_end=93
  _globals['_ALLFLAGS']._serialized_start=95
  _globals['_ALLFLAGS']._serialized_end=141
  _globals['_NOTIFICATION']._serialized_start=144
  _globals['_NOTIFICATION']._serialized_end=324
  _globals['_NOTIFICATION_UNSUBSCRIBECOMPLETE']._serialized_start=287
  _globals['_NOTIFICATION_UNSUBSCRIBECOMPLETE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
