# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: networklink.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'networklink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import applicationInfo_pb2 as applicationInfo__pb2
import customOptions_pb2 as customOptions__pb2
import proApi_pb2 as proApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11networklink.proto\x12\x07rv.data\x1a\x15\x61pplicationInfo.proto\x1a\x13\x63ustomOptions.proto\x1a\x0cproApi.proto\"\x90\x01\n\x13NetworkLinkDocument\x12\x34\n\ngroup_info\x18\x01 \x01(\x0b\x32 .rv.data.ProLink.GroupDefinition\x12\x32\n\x10\x61pplication_info\x18\x02 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\"\xe3\x02\n\x11NetworkLinkStatus\x12;\n\x0cstatus_pairs\x18\x01 \x03(\x0b\x32%.rv.data.NetworkLinkStatus.StatusPair\x1a\x88\x01\n\x17LinkedClientInformation\x12\x33\n\x08platform\x18\x01 \x01(\x0e\x32!.rv.data.ApplicationInfo.Platform\x12\x12\n\nos_version\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x1a\x85\x01\n\nStatusPair\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12U\n\x19linked_client_information\x18\x03 \x01(\x0b\x32\x32.rv.data.NetworkLinkStatus.LinkedClientInformationB4\xf8\x01\x01\xaa\x02$Pro.SerializationInterop.RVProtoData\xba\x02\x07RVData_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'networklink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002$Pro.SerializationInterop.RVProtoData\272\002\007RVData_'
  _globals['_NETWORKLINKDOCUMENT']._serialized_start=89
  _globals['_NETWORKLINKDOCUMENT']._serialized_end=233
  _globals['_NETWORKLINKSTATUS']._serialized_start=236
  _globals['_NETWORKLINKSTATUS']._serialized_end=591
  _globals['_NETWORKLINKSTATUS_LINKEDCLIENTINFORMATION']._serialized_start=319
  _globals['_NETWORKLINKSTATUS_LINKEDCLIENTINFORMATION']._serialized_end=455
  _globals['_NETWORKLINKSTATUS_STATUSPAIR']._serialized_start=458
  _globals['_NETWORKLINKSTATUS_STATUSPAIR']._serialized_end=591
# @@protoc_insertion_point(module_scope)
