# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: params.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import v1_helper_common_pb2 as v1__helper__common__pb2
import v2_helper_common_pb2 as v2__helper__common__pb2
import feature_flags_pb2 as feature__flags__pb2
from document import bootstrap_pb2 as document_dot_bootstrap__pb2
from workspace import bootstrap_pb2 as workspace_dot_bootstrap__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparams.proto\x12\x0b\x61pplication\x1a\x16v1-helper-common.proto\x1a\x16v2-helper-common.proto\x1a\x13\x66\x65\x61ture-flags.proto\x1a\x18\x64ocument.bootstrap.proto\x1a\x19workspace.bootstrap.proto\"\x99\x01\n\x12ProductInformation\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x15\n\rmajor_version\x18\x02 \x01(\t\x12\x15\n\rminor_version\x18\x03 \x01(\t\x12\x15\n\rpatch_version\x18\x04 \x01(\t\x12\x14\n\x0c\x62uild_number\x18\x05 \x01(\t\x12\x12\n\nbuild_date\x18\x06 \x01(\x03\"\x86\x01\n\x11\x41pplicationParams\x12\x35\n\x0cproduct_info\x18\x01 \x01(\x0b\x32\x1f.application.ProductInformation\x12\x18\n\x10\x65nabled_features\x18\x02 \x03(\t\x12\x14\n\x07peer_id\x18\x03 \x01(\x04H\x00\x88\x01\x01\x42\n\n\x08_peer_id\"\x87\x03\n\x16\x41pplicationStartParams\x12\x33\n\x0b\x61pplication\x18\x01 \x01(\x0b\x32\x1e.application.ApplicationParams\x12\x32\n\x08media_v1\x18\x02 \x01(\x0b\x32 .helper.common.v1.CreationOption\x12/\n\x05media\x18\x03 \x01(\x0b\x32 .helper.common.v2.CreationOption\x12\x34\n\rfeature_flags\x18\x04 \x01(\x0b\x32\x1d.feature_flags.CreationOption\x12=\n\x0cregistration\x18\x06 \x01(\x0b\x32\'.application.RegistrationCreationOption\x12*\n\x08\x64ocument\x18\x07 \x01(\x0b\x32\x18.document.CreationOption\x12,\n\tworkspace\x18\x08 \x01(\x0b\x32\x19.workspace.CreationOptionJ\x04\x08\x05\x10\x06\"\x1c\n\x1aRegistrationCreationOption\"3\n\x08Shutdown\x12\x0c\n\x02ok\x18\x01 \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x08\n\x06resultBI\xaa\x02\x30Pro.SerializationInterop.RVProtoData.Application\xba\x02\x13RVData_Application_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0020Pro.SerializationInterop.RVProtoData.Application\272\002\023RVData_Application_'
  _globals['_PRODUCTINFORMATION']._serialized_start=152
  _globals['_PRODUCTINFORMATION']._serialized_end=305
  _globals['_APPLICATIONPARAMS']._serialized_start=308
  _globals['_APPLICATIONPARAMS']._serialized_end=442
  _globals['_APPLICATIONSTARTPARAMS']._serialized_start=445
  _globals['_APPLICATIONSTARTPARAMS']._serialized_end=836
  _globals['_REGISTRATIONCREATIONOPTION']._serialized_start=838
  _globals['_REGISTRATIONCREATIONOPTION']._serialized_end=866
  _globals['_SHUTDOWN']._serialized_start=868
  _globals['_SHUTDOWN']._serialized_end=919
# @@protoc_insertion_point(module_scope)
