# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pptparams.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pptparams.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpptparams.proto\x12\tpptimport\"\x87\x01\n\x0fPPTImportParams\x12\x11\n\tpptx_path\x18\x01 \x01(\t\x12\x1a\n\x12result_folder_path\x18\x02 \x01(\t\x12\x13\n\x0bslide_width\x18\x03 \x01(\r\x12\x14\n\x0cslide_height\x18\x04 \x01(\r\x12\x1a\n\x12ignore_backgrounds\x18\x05 \x01(\x08\x42\x45\xaa\x02.Pro.SerializationInterop.RVProtoData.PPTImport\xba\x02\x11RVData_PPTImport_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pptparams_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002.Pro.SerializationInterop.RVProtoData.PPTImport\272\002\021RVData_PPTImport_'
  _globals['_PPTIMPORTPARAMS']._serialized_start=31
  _globals['_PPTIMPORTPARAMS']._serialized_end=166
# @@protoc_insertion_point(module_scope)
