# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proCoreFeatureFlags.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proCoreFeatureFlags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proCoreFeatureFlags.proto\x12\x07rv.data\"\xea\x02\n\x14ResolvedFeatureFlags\x12%\n\x1d\x63ontent_store_staging_enabled\x18\x01 \x01(\x08\x12$\n\x1cstaging_api_endpoint_enabled\x18\x08 \x01(\x08\x12#\n\x1bpro_content_staging_enabled\x18\n \x01(\x08\x12 \n\x18\x63ore_networkapi_playlist\x18\x0b \x01(\x08\x12$\n\x1c\x63ore_networkapi_presentation\x18\x0c \x01(\x08\x12\x18\n\x10\x63ore_client_sync\x18\x0f \x01(\x08\x12\x1d\n\x15hdr_rendering_enabled\x18\x11 \x01(\x08\x12#\n\x1bserver_driven_feature_flags\x18\x12 \x01(\x08J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\t\x10\nJ\x04\x08\r\x10\x0eJ\x04\x08\x0e\x10\x0fJ\x04\x08\x10\x10\x11\x42\x34\xf8\x01\x01\xaa\x02$Pro.SerializationInterop.RVProtoData\xba\x02\x07RVData_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proCoreFeatureFlags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002$Pro.SerializationInterop.RVProtoData\272\002\007RVData_'
  _globals['_RESOLVEDFEATUREFLAGS']._serialized_start=39
  _globals['_RESOLVEDFEATUREFLAGS']._serialized_end=401
# @@protoc_insertion_point(module_scope)
