# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: propSlide.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'propSlide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import customOptions_pb2 as customOptions__pb2
import slide_pb2 as slide__pb2
import effects_pb2 as effects__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpropSlide.proto\x12\x07rv.data\x1a\x13\x63ustomOptions.proto\x1a\x0bslide.proto\x1a\reffects.proto\"\x91\x01\n\tPropSlide\x12\"\n\nbase_slide\x18\x01 \x01(\x0b\x32\x0e.rv.data.Slide\x12\'\n\ntransition\x18\x02 \x01(\x0b\x32\x13.rv.data.Transition\x12\x1a\n\x12\x61uto_clear_enabled\x18\x03 \x01(\x08\x12\x1b\n\x13\x61uto_clear_duration\x18\x04 \x01(\x01\x42\x34\xf8\x01\x01\xaa\x02$Pro.SerializationInterop.RVProtoData\xba\x02\x07RVData_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'propSlide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002$Pro.SerializationInterop.RVProtoData\272\002\007RVData_'
  _globals['_PROPSLIDE']._serialized_start=78
  _globals['_PROPSLIDE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
