# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: psbWorkspace.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'psbWorkspace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import advertisementGroup_pb2 as advertisementGroup__pb2
import digitalAudio_pb2 as digitalAudio__pb2
import input_pb2 as input__pb2
import proscreen_pb2 as proscreen__pb2
import recording_pb2 as recording__pb2
import zone_pb2 as zone__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12psbWorkspace.proto\x12\x07rv.data\x1a\x18\x61\x64vertisementGroup.proto\x1a\x12\x64igitalAudio.proto\x1a\x0binput.proto\x1a\x0fproscreen.proto\x1a\x0frecording.proto\x1a\nzone.proto\"\x8f\x03\n\x16ProScoreboardWorkspace\x12\x30\n\x0bpro_screens\x18\x01 \x03(\x0b\x32\x1b.rv.data.ProPresenterScreen\x12(\n\x0bvideoInputs\x18\x02 \x03(\x0b\x32\x13.rv.data.VideoInput\x12<\n\x0frecord_settings\x18\x03 \x01(\x0b\x32#.rv.data.Recording.SettingsDocument\x12\x38\n\x13\x64igital_audio_setup\x18\x04 \x01(\x0b\x32\x1b.rv.data.DigitalAudio.Setup\x12)\n\x0c\x61udio_inputs\x18\x05 \x03(\x0b\x32\x13.rv.data.AudioInput\x12#\n\x1b\x61udio_input_transition_time\x18\x06 \x01(\x01\x12\x1c\n\x05zones\x18\x07 \x03(\x0b\x32\r.rv.data.Zone\x12\x33\n\x0e\x61\x64vertisements\x18\x08 \x03(\x0b\x32\x1b.rv.data.AdvertisementGroupB4\xf8\x01\x01\xaa\x02$Pro.SerializationInterop.RVProtoData\xba\x02\x07RVData_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'psbWorkspace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001\252\002$Pro.SerializationInterop.RVProtoData\272\002\007RVData_'
  _globals['_PROSCOREBOARDWORKSPACE']._serialized_start=137
  _globals['_PROSCOREBOARDWORKSPACE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
