# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rverror.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rverror.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrverror.proto\x12\x07rverror\"\xa5\x01\n\rReportedError\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\x12\x0c\n\x04line\x18\x04 \x01(\r\x12\x31\n\x08severity\x18\x05 \x01(\x0e\x32\x1f.rverror.ReportedError.Severity\"\"\n\x08Severity\x12\x0b\n\x07HANDLED\x10\x00\x12\t\n\x05\x46\x41TAL\x10\x01\x42\x41\xaa\x02,Pro.SerializationInterop.RVProtoData.RVError\xba\x02\x0fRVData_RVError_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rverror_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002,Pro.SerializationInterop.RVProtoData.RVError\272\002\017RVData_RVError_'
  _globals['_REPORTEDERROR']._serialized_start=27
  _globals['_REPORTEDERROR']._serialized_end=192
  _globals['_REPORTEDERROR_SEVERITY']._serialized_start=158
  _globals['_REPORTEDERROR_SEVERITY']._serialized_end=192
# @@protoc_insertion_point(module_scope)
