# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workspace.bootstrap.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'workspace.bootstrap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19workspace.bootstrap.proto\x12\tworkspace\"B\n\x0e\x43reationOption\x12\x1c\n\x0fmin_pro_version\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x12\n\x10_min_pro_versionBU\xaa\x02\x36Pro.SerializationInterop.RVProtoData.Service.Workspace\xba\x02\x19RVData_Service_Workspace_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace.bootstrap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0026Pro.SerializationInterop.RVProtoData.Service.Workspace\272\002\031RVData_Service_Workspace_'
  _globals['_CREATIONOPTION']._serialized_start=40
  _globals['_CREATIONOPTION']._serialized_end=106
# @@protoc_insertion_point(module_scope)
