# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workspace.notifications.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'workspace.notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from workspace.entities import remote_pb2 as workspace_dot_entities_dot_remote__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dworkspace.notifications.proto\x12\tworkspace\x1a\x1fworkspace.entities.remote.proto\"\x95\x06\n\x0cNotification\x12\x42\n\x0bunsubscribe\x18\x01 \x01(\x0b\x32+.workspace.Notification.UnsubscribeCompleteH\x00\x12\x38\n\nworkspaces\x18\x02 \x01(\x0b\x32\".workspace.Notification.WorkspacesH\x00\x12>\n\rcollaborators\x18\x03 \x01(\x0b\x32%.workspace.Notification.CollaboratorsH\x00\x12\x32\n\x07syncing\x18\x04 \x01(\x0b\x32\x1f.workspace.Notification.SyncingH\x00\x1a\x15\n\x13UnsubscribeComplete\x1a\xbf\x02\n\nWorkspaces\x12G\n\x0binitialized\x18\x01 \x01(\x0b\x32\x30.workspace.Notification.Workspaces.WorkspaceListH\x00\x12I\n\runinitialized\x18\x02 \x01(\x0b\x32\x30.workspace.Notification.Workspaces.UninitializedH\x00\x12\x39\n\x05\x65rror\x18\x03 \x01(\x0b\x32(.workspace.Notification.Workspaces.ErrorH\x00\x1a?\n\rWorkspaceList\x12.\n\nworkspaces\x18\x01 \x03(\x0b\x32\x1a.workspace.remote.Metadata\x1a\x0f\n\rUninitialized\x1a\x07\n\x05\x45rrorB\x07\n\x05state\x1a\x1f\n\rCollaborators\x12\x0e\n\x06online\x18\x01 \x03(\t\x1a\x88\x01\n\x07Syncing\x12;\n\x06paused\x18\x01 \x01(\x0b\x32&.workspace.Notification.Syncing.PausedH\x00\x88\x01\x01\x1a\x35\n\x06Paused\x12\x16\n\x0euntil_time_utc\x18\x01 \x01(\x04\x12\x13\n\x0b\x61t_time_utc\x18\x02 \x01(\x04\x42\t\n\x07_pausedB\x0e\n\x0cnotificationBU\xaa\x02\x36Pro.SerializationInterop.RVProtoData.Service.Workspace\xba\x02\x19RVData_Service_Workspace_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0026Pro.SerializationInterop.RVProtoData.Service.Workspace\272\002\031RVData_Service_Workspace_'
  _globals['_NOTIFICATION']._serialized_start=78
  _globals['_NOTIFICATION']._serialized_end=867
  _globals['_NOTIFICATION_UNSUBSCRIBECOMPLETE']._serialized_start=336
  _globals['_NOTIFICATION_UNSUBSCRIBECOMPLETE']._serialized_end=357
  _globals['_NOTIFICATION_WORKSPACES']._serialized_start=360
  _globals['_NOTIFICATION_WORKSPACES']._serialized_end=679
  _globals['_NOTIFICATION_WORKSPACES_WORKSPACELIST']._serialized_start=581
  _globals['_NOTIFICATION_WORKSPACES_WORKSPACELIST']._serialized_end=644
  _globals['_NOTIFICATION_WORKSPACES_UNINITIALIZED']._serialized_start=646
  _globals['_NOTIFICATION_WORKSPACES_UNINITIALIZED']._serialized_end=661
  _globals['_NOTIFICATION_WORKSPACES_ERROR']._serialized_start=663
  _globals['_NOTIFICATION_WORKSPACES_ERROR']._serialized_end=670
  _globals['_NOTIFICATION_COLLABORATORS']._serialized_start=681
  _globals['_NOTIFICATION_COLLABORATORS']._serialized_end=712
  _globals['_NOTIFICATION_SYNCING']._serialized_start=715
  _globals['_NOTIFICATION_SYNCING']._serialized_end=851
  _globals['_NOTIFICATION_SYNCING_PAUSED']._serialized_start=787
  _globals['_NOTIFICATION_SYNCING_PAUSED']._serialized_end=840
# @@protoc_insertion_point(module_scope)
