# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.entities.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'document.entities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64ocument.entities.proto\x12\x08\x64ocument\"\x15\n\x05Ready\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x08\n\x06Remote\"\x1a\n\x05Local\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"\xd8\x02\n\tIntrinsic\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12&\n\x04kind\x18\x02 \x01(\x0e\x32\x18.document.Intrinsic.Kind\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"\x86\x02\n\x04Kind\x12\x0c\n\x08\x43\x61lendar\x10\x00\x12\x08\n\x04\x43\x43LI\x10\x01\x12\x0f\n\x0b\x43learGroups\x10\x02\x12\n\n\x06Groups\x10\x03\x12\x0f\n\x0bKeyMappings\x10\x04\x12\n\n\x06Labels\x10\x05\x12\n\n\x06Macros\x10\x06\x12\x0c\n\x08Messages\x10\x07\x12\t\n\x05Props\x10\x08\x12\t\n\x05Stage\x10\t\x12\n\n\x06Timers\x10\n\x12\r\n\tWorkspace\x10\x0b\x12\x0f\n\x0bLibraryData\x10\x0c\x12\x11\n\rPlaylistAudio\x10\r\x12\x13\n\x0fPlaylistLibrary\x10\x0e\x12\x11\n\rPlaylistMedia\x10\x0f\x12\x15\n\x11PlaylistTemplates\x10\x10\"\xbb\x01\n\x08\x44ocument\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12 \n\x05ready\x18\n \x01(\x0b\x32\x0f.document.ReadyH\x00\x12 \n\x05local\x18\x0b \x01(\x0b\x32\x0f.document.LocalH\x00\x12\"\n\x06remote\x18\x0c \x01(\x0b\x32\x10.document.RemoteH\x00\"#\n\x04Kind\x12\x10\n\x0cPRESENTATION\x10\x00\x12\t\n\x05THEME\x10\x01\x42\x06\n\x04\x62ody\"\x85\x01\n\x0b\x44ocumentSet\x12\'\n\nintrinsics\x18\x01 \x03(\x0b\x32\x13.document.Intrinsic\x12)\n\rpresentations\x18\x02 \x03(\x0b\x32\x12.document.Document\x12\"\n\x06themes\x18\x03 \x03(\x0b\x32\x12.document.DocumentBS\xaa\x02\x35Pro.SerializationInterop.RVProtoData.Service.Document\xba\x02\x18RVData_Service_Document_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document.entities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0025Pro.SerializationInterop.RVProtoData.Service.Document\272\002\030RVData_Service_Document_'
  _globals['_READY']._serialized_start=37
  _globals['_READY']._serialized_end=58
  _globals['_REMOTE']._serialized_start=60
  _globals['_REMOTE']._serialized_end=68
  _globals['_LOCAL']._serialized_start=70
  _globals['_LOCAL']._serialized_end=96
  _globals['_INTRINSIC']._serialized_start=99
  _globals['_INTRINSIC']._serialized_end=443
  _globals['_INTRINSIC_KIND']._serialized_start=181
  _globals['_INTRINSIC_KIND']._serialized_end=443
  _globals['_DOCUMENT']._serialized_start=446
  _globals['_DOCUMENT']._serialized_end=633
  _globals['_DOCUMENT_KIND']._serialized_start=590
  _globals['_DOCUMENT_KIND']._serialized_end=625
  _globals['_DOCUMENTSET']._serialized_start=636
  _globals['_DOCUMENTSET']._serialized_end=769
# @@protoc_insertion_point(module_scope)
