# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.notifications.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'document.notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from document import entities_pb2 as document_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64ocument.notifications.proto\x12\x08\x64ocument\x1a\x17\x64ocument.entities.proto\"\xf2\x05\n\x0cNotification\x12\x41\n\x0bunsubscribe\x18\x01 \x01(\x0b\x32*.document.Notification.UnsubscribeCompleteH\x00\x12-\n\x05patch\x18\x02 \x01(\x0b\x32\x1c.document.Notification.PatchH\x00\x12\x33\n\x08required\x18\x03 \x01(\x0b\x32\x1f.document.Notification.RequiredH\x00\x12\x35\n\tavailable\x18\x04 \x01(\x0b\x32 .document.Notification.AvailableH\x00\x12-\n\x05\x61\x64\x64\x65\x64\x18\x05 \x01(\x0b\x32\x1c.document.Notification.AddedH\x00\x12-\n\x05moved\x18\x06 \x01(\x0b\x32\x1c.document.Notification.MovedH\x00\x12\x31\n\x07removed\x18\x07 \x01(\x0b\x32\x1e.document.Notification.RemovedH\x00\x1a\x15\n\x13UnsubscribeComplete\x1a#\n\x05Patch\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62lob\x18\x02 \x01(\x0c\x1a\x18\n\x08Required\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x1a\'\n\tAvailable\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62lob\x18\x02 \x01(\x0c\x1aJ\n\x05\x41\x64\x64\x65\x64\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12%\n\x04kind\x18\x02 \x01(\x0e\x32\x17.document.Document.Kind\x12\x0c\n\x04path\x18\x03 \x01(\t\x1aJ\n\x05Moved\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12%\n\x04kind\x18\x02 \x01(\x0e\x32\x17.document.Document.Kind\x12\x0c\n\x04path\x18\x03 \x01(\t\x1aL\n\x07Removed\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12%\n\x04kind\x18\x02 \x01(\x0e\x32\x17.document.Document.Kind\x12\x0c\n\x04path\x18\x03 \x01(\tB\x0e\n\x0cnotificationBS\xaa\x02\x35Pro.SerializationInterop.RVProtoData.Service.Document\xba\x02\x18RVData_Service_Document_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0025Pro.SerializationInterop.RVProtoData.Service.Document\272\002\030RVData_Service_Document_'
  _globals['_NOTIFICATION']._serialized_start=68
  _globals['_NOTIFICATION']._serialized_end=822
  _globals['_NOTIFICATION_UNSUBSCRIBECOMPLETE']._serialized_start=451
  _globals['_NOTIFICATION_UNSUBSCRIBECOMPLETE']._serialized_end=472
  _globals['_NOTIFICATION_PATCH']._serialized_start=474
  _globals['_NOTIFICATION_PATCH']._serialized_end=509
  _globals['_NOTIFICATION_REQUIRED']._serialized_start=511
  _globals['_NOTIFICATION_REQUIRED']._serialized_end=535
  _globals['_NOTIFICATION_AVAILABLE']._serialized_start=537
  _globals['_NOTIFICATION_AVAILABLE']._serialized_end=576
  _globals['_NOTIFICATION_ADDED']._serialized_start=578
  _globals['_NOTIFICATION_ADDED']._serialized_end=652
  _globals['_NOTIFICATION_MOVED']._serialized_start=654
  _globals['_NOTIFICATION_MOVED']._serialized_end=728
  _globals['_NOTIFICATION_REMOVED']._serialized_start=730
  _globals['_NOTIFICATION_REMOVED']._serialized_end=806
# @@protoc_insertion_point(module_scope)
