# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workspace.entities.remote.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'workspace.entities.remote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from document import entities_pb2 as document_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fworkspace.entities.remote.proto\x12\x10workspace.remote\x1a\x17\x64ocument.entities.proto\"k\n\x08Metadata\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0bpro_version\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\n \x01(\x04\x12\x0f\n\x07\x63reated\x18\x0b \x01(\x04\x12\x0f\n\x07updated\x18\x0c \x01(\x04\"c\n\tWorkspace\x12,\n\x08metadata\x18\x01 \x01(\x0b\x32\x1a.workspace.remote.Metadata\x12(\n\tdocuments\x18\x02 \x01(\x0b\x32\x15.document.DocumentSetBc\xaa\x02=Pro.SerializationInterop.RVProtoData.Service.Workspace.Remote\xba\x02 RVData_Service_Workspace_Remote_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace.entities.remote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002=Pro.SerializationInterop.RVProtoData.Service.Workspace.Remote\272\002 RVData_Service_Workspace_Remote_'
  _globals['_METADATA']._serialized_start=78
  _globals['_METADATA']._serialized_end=185
  _globals['_WORKSPACE']._serialized_start=187
  _globals['_WORKSPACE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
